# Generated by Django 5.1.5 on 2025-01-25 11:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_wantedposter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('movie', 'Filme'), ('series', 'Série')], max_length=10)),
                ('media_title', models.CharField(max_length=200)),
                ('review_title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'A nota mínima é 1'), django.core.validators.MaxValueValidator(10, 'A nota máxima é 10')])),
                ('episode_number', models.CharField(blank=True, max_length=50, null=True)),
                ('media_image', models.FileField(blank=True, null=True, upload_to='review_media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WantedPoster',
        ),
    ]
